"""initial_schema

Revision ID: c0820e85296d
Revises: 
Create Date: 2026-01-03 12:13:24.537571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0820e85296d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buffets',
    sa.Column('nombre', sa.String(length=255), nullable=False, comment='Nombre del estudio jurídico'),
    sa.Column('rut', sa.String(length=12), nullable=False, comment='RUT único del buffet'),
    sa.Column('email_principal', sa.String(length=255), nullable=False, comment='Email de contacto principal'),
    sa.Column('telefono', sa.String(length=20), nullable=True, comment='Teléfono de contacto'),
    sa.Column('contacto_nombre', sa.String(length=255), nullable=True, comment='Nombre de la persona de contacto'),
    sa.Column('token_tablero', sa.String(length=64), nullable=False, comment='Token para acceso al tablero público'),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Si el buffet está activo'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_tablero')
    )
    op.create_index(op.f('ix_buffets_id'), 'buffets', ['id'], unique=False)
    op.create_index(op.f('ix_buffets_rut'), 'buffets', ['rut'], unique=True)
    op.create_table('usuarios',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email único para login'),
    sa.Column('nombre', sa.String(length=255), nullable=False, comment='Nombre completo del usuario'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hash bcrypt de la contraseña'),
    sa.Column('rol', sa.Enum('ADMIN', 'INVESTIGADOR', 'CLIENTE', name='rol_enum'), nullable=False, comment='Rol del usuario en el sistema'),
    sa.Column('buffet_id', sa.Integer(), nullable=True, comment='ID del buffet (solo para clientes)'),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Si el usuario está activo'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='URL del avatar del usuario'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buffet_id'], ['buffets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_buffet_id'), 'usuarios', ['buffet_id'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('oficios',
    sa.Column('numero_oficio', sa.String(length=50), nullable=False, comment='Número único del oficio (ej: OF-2024-001)'),
    sa.Column('buffet_id', sa.Integer(), nullable=False, comment='ID del buffet que solicitó la investigación'),
    sa.Column('investigador_id', sa.Integer(), nullable=True, comment='ID del investigador asignado'),
    sa.Column('estado', sa.Enum('PENDIENTE', 'INVESTIGACION', 'NOTIFICACION', 'FINALIZADO_ENCONTRADO', 'FINALIZADO_NO_ENCONTRADO', name='estado_oficio_enum'), nullable=False, comment='Estado actual del oficio'),
    sa.Column('prioridad', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'URGENTE', name='prioridad_enum'), nullable=False, comment='Nivel de prioridad'),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False, comment='Fecha de ingreso del oficio'),
    sa.Column('fecha_limite', sa.Date(), nullable=True, comment='Fecha límite para completar'),
    sa.Column('notas_generales', sa.Text(), nullable=True, comment='Notas o comentarios generales'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buffet_id'], ['buffets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigador_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oficios_buffet_id'), 'oficios', ['buffet_id'], unique=False)
    op.create_index(op.f('ix_oficios_estado'), 'oficios', ['estado'], unique=False)
    op.create_index(op.f('ix_oficios_id'), 'oficios', ['id'], unique=False)
    op.create_index(op.f('ix_oficios_investigador_id'), 'oficios', ['investigador_id'], unique=False)
    op.create_index(op.f('ix_oficios_numero_oficio'), 'oficios', ['numero_oficio'], unique=True)
    op.create_table('adjuntos',
    sa.Column('oficio_id', sa.Integer(), nullable=False, comment='ID del oficio'),
    sa.Column('investigador_id', sa.Integer(), nullable=True, comment='ID del usuario que subió el adjunto'),
    sa.Column('tipo', sa.Enum('FOTO_VEHICULO', 'DOCUMENTO', 'EVIDENCIA', name='tipo_adjunto_enum'), nullable=False, comment='Tipo de adjunto'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Nombre del archivo'),
    sa.Column('url', sa.String(length=500), nullable=False, comment='Path o URL del archivo'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='Tipo MIME del archivo'),
    sa.Column('tamaño_bytes', sa.Integer(), nullable=True, comment='Tamaño en bytes'),
    sa.Column('descripcion', sa.Text(), nullable=True, comment='Descripción del adjunto'),
    sa.Column('fecha_subida', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de subida'),
    sa.Column('metadata_json', sa.Text(), nullable=True, comment='Metadata adicional en JSON (GPS, EXIF)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigador_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['oficio_id'], ['oficios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjuntos_id'), 'adjuntos', ['id'], unique=False)
    op.create_index(op.f('ix_adjuntos_oficio_id'), 'adjuntos', ['oficio_id'], unique=False)
    op.create_table('avistamientos',
    sa.Column('oficio_id', sa.Integer(), nullable=False, comment='ID del oficio'),
    sa.Column('fuente', sa.Enum('PORTICO', 'MULTA', 'TERRENO', name='fuente_avistamiento_enum'), nullable=False, comment='Fuente del avistamiento'),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora del avistamiento'),
    sa.Column('ubicacion', sa.String(length=500), nullable=False, comment='Ubicación textual del avistamiento'),
    sa.Column('latitud', sa.Float(), nullable=True, comment='Latitud del avistamiento'),
    sa.Column('longitud', sa.Float(), nullable=True, comment='Longitud del avistamiento'),
    sa.Column('api_response_id', sa.String(length=100), nullable=True, comment='ID de la respuesta de la API externa'),
    sa.Column('datos_json', sa.Text(), nullable=True, comment='Datos adicionales en formato JSON'),
    sa.Column('notas', sa.Text(), nullable=True, comment='Notas adicionales'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['oficio_id'], ['oficios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avistamientos_fecha_hora'), 'avistamientos', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_avistamientos_id'), 'avistamientos', ['id'], unique=False)
    op.create_index(op.f('ix_avistamientos_oficio_id'), 'avistamientos', ['oficio_id'], unique=False)
    op.create_table('direcciones',
    sa.Column('oficio_id', sa.Integer(), nullable=False, comment='ID del oficio'),
    sa.Column('direccion', sa.String(length=500), nullable=False, comment='Dirección completa'),
    sa.Column('comuna', sa.String(length=100), nullable=True, comment='Comuna'),
    sa.Column('region', sa.String(length=100), nullable=True, comment='Región'),
    sa.Column('tipo', sa.Enum('DOMICILIO', 'TRABAJO', 'FAMILIAR', 'OTRO', name='tipo_direccion_enum'), nullable=False, comment='Tipo de dirección'),
    sa.Column('verificada', sa.Boolean(), nullable=False, comment='Si fue verificada en terreno'),
    sa.Column('fecha_verificacion', sa.DateTime(timezone=True), nullable=True, comment='Fecha y hora de verificación'),
    sa.Column('notas', sa.Text(), nullable=True, comment='Notas adicionales'),
    sa.Column('agregada_por_id', sa.Integer(), nullable=True, comment='ID del usuario que agregó la dirección'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agregada_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['oficio_id'], ['oficios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direcciones_id'), 'direcciones', ['id'], unique=False)
    op.create_index(op.f('ix_direcciones_oficio_id'), 'direcciones', ['oficio_id'], unique=False)
    op.create_table('investigaciones',
    sa.Column('oficio_id', sa.Integer(), nullable=False, comment='ID del oficio'),
    sa.Column('investigador_id', sa.Integer(), nullable=True, comment='ID del investigador que realizó la actividad'),
    sa.Column('tipo_actividad', sa.Enum('CONSULTA_API', 'NOTA', 'LLAMADA', 'TERRENO', name='tipo_actividad_enum'), nullable=False, comment='Tipo de actividad'),
    sa.Column('descripcion', sa.Text(), nullable=False, comment='Descripción de la actividad'),
    sa.Column('resultado', sa.Text(), nullable=True, comment='Resultado obtenido'),
    sa.Column('api_externa', sa.String(length=100), nullable=True, comment='Nombre de la API externa si aplica'),
    sa.Column('datos_json', sa.Text(), nullable=True, comment='Datos adicionales en formato JSON'),
    sa.Column('fecha_actividad', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora de la actividad'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigador_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['oficio_id'], ['oficios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigaciones_fecha_actividad'), 'investigaciones', ['fecha_actividad'], unique=False)
    op.create_index(op.f('ix_investigaciones_id'), 'investigaciones', ['id'], unique=False)
    op.create_index(op.f('ix_investigaciones_oficio_id'), 'investigaciones', ['oficio_id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('oficio_id', sa.Integer(), nullable=False, comment='ID del oficio'),
    sa.Column('tipo', sa.Enum('RECEPTOR_JUDICIAL', 'BUFFET', 'INTERNA', name='tipo_notificacion_enum'), nullable=False, comment='Tipo de notificación'),
    sa.Column('destinatario', sa.String(length=255), nullable=False, comment='Email o identificador del destinatario'),
    sa.Column('asunto', sa.String(length=500), nullable=True, comment='Asunto del email/notificación'),
    sa.Column('contenido', sa.Text(), nullable=True, comment='Contenido del mensaje'),
    sa.Column('enviada', sa.Boolean(), nullable=False, comment='Si fue enviada exitosamente'),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True, comment='Fecha y hora de envío exitoso'),
    sa.Column('intentos', sa.Integer(), nullable=False, comment='Número de intentos de envío'),
    sa.Column('error_mensaje', sa.Text(), nullable=True, comment='Mensaje de error si falló'),
    sa.Column('metadata_json', sa.Text(), nullable=True, comment='Metadata adicional en JSON'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['oficio_id'], ['oficios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_enviada'), 'notificaciones', ['enviada'], unique=False)
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_index(op.f('ix_notificaciones_oficio_id'), 'notificaciones', ['oficio_id'], unique=False)
    op.create_table('propietarios',
    sa.Column('oficio_id', sa.Integer(), nullable=False, comment='ID del oficio'),
    sa.Column('rut', sa.String(length=12), nullable=False, comment='RUT del propietario'),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False, comment='Nombre completo'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email de contacto'),
    sa.Column('telefono', sa.String(length=20), nullable=True, comment='Teléfono de contacto'),
    sa.Column('tipo', sa.Enum('PRINCIPAL', 'CODEUDOR', 'AVAL', 'USUARIO', name='tipo_propietario_enum'), nullable=False, comment='Tipo de propietario'),
    sa.Column('direccion_principal', sa.String(length=500), nullable=True, comment='Dirección principal conocida'),
    sa.Column('notas', sa.Text(), nullable=True, comment='Notas adicionales'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['oficio_id'], ['oficios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propietarios_id'), 'propietarios', ['id'], unique=False)
    op.create_index(op.f('ix_propietarios_oficio_id'), 'propietarios', ['oficio_id'], unique=False)
    op.create_index(op.f('ix_propietarios_rut'), 'propietarios', ['rut'], unique=False)
    op.create_table('vehiculos',
    sa.Column('oficio_id', sa.Integer(), nullable=False, comment='ID del oficio (relación 1:1)'),
    sa.Column('patente', sa.String(length=10), nullable=False, comment='Patente del vehículo'),
    sa.Column('marca', sa.String(length=100), nullable=True, comment='Marca del vehículo'),
    sa.Column('modelo', sa.String(length=100), nullable=True, comment='Modelo del vehículo'),
    sa.Column('año', sa.Integer(), nullable=True, comment='Año del vehículo'),
    sa.Column('color', sa.String(length=50), nullable=True, comment='Color del vehículo'),
    sa.Column('vin', sa.String(length=17), nullable=True, comment='Número de identificación vehicular (VIN)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['oficio_id'], ['oficios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_id'), 'vehiculos', ['id'], unique=False)
    op.create_index(op.f('ix_vehiculos_oficio_id'), 'vehiculos', ['oficio_id'], unique=True)
    op.create_index(op.f('ix_vehiculos_patente'), 'vehiculos', ['patente'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehiculos_patente'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_oficio_id'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_id'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_index(op.f('ix_propietarios_rut'), table_name='propietarios')
    op.drop_index(op.f('ix_propietarios_oficio_id'), table_name='propietarios')
    op.drop_index(op.f('ix_propietarios_id'), table_name='propietarios')
    op.drop_table('propietarios')
    op.drop_index(op.f('ix_notificaciones_oficio_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_enviada'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_investigaciones_oficio_id'), table_name='investigaciones')
    op.drop_index(op.f('ix_investigaciones_id'), table_name='investigaciones')
    op.drop_index(op.f('ix_investigaciones_fecha_actividad'), table_name='investigaciones')
    op.drop_table('investigaciones')
    op.drop_index(op.f('ix_direcciones_oficio_id'), table_name='direcciones')
    op.drop_index(op.f('ix_direcciones_id'), table_name='direcciones')
    op.drop_table('direcciones')
    op.drop_index(op.f('ix_avistamientos_oficio_id'), table_name='avistamientos')
    op.drop_index(op.f('ix_avistamientos_id'), table_name='avistamientos')
    op.drop_index(op.f('ix_avistamientos_fecha_hora'), table_name='avistamientos')
    op.drop_table('avistamientos')
    op.drop_index(op.f('ix_adjuntos_oficio_id'), table_name='adjuntos')
    op.drop_index(op.f('ix_adjuntos_id'), table_name='adjuntos')
    op.drop_table('adjuntos')
    op.drop_index(op.f('ix_oficios_numero_oficio'), table_name='oficios')
    op.drop_index(op.f('ix_oficios_investigador_id'), table_name='oficios')
    op.drop_index(op.f('ix_oficios_id'), table_name='oficios')
    op.drop_index(op.f('ix_oficios_estado'), table_name='oficios')
    op.drop_index(op.f('ix_oficios_buffet_id'), table_name='oficios')
    op.drop_table('oficios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_buffet_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_buffets_rut'), table_name='buffets')
    op.drop_index(op.f('ix_buffets_id'), table_name='buffets')
    op.drop_table('buffets')
    # ### end Alembic commands ###

