"""create_documentos_procesados

Revision ID: e198791a2934
Revises: b2c3d4e5f6g7
Create Date: 2026-01-11 16:56:44.012636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e198791a2934'
down_revision: Union[str, None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentos_procesados',
    sa.Column('drive_file_id', sa.String(length=255), nullable=False, comment='ID único del archivo en Google Drive'),
    sa.Column('drive_file_name', sa.String(length=500), nullable=False, comment='Nombre del archivo en Google Drive'),
    sa.Column('drive_folder_id', sa.String(length=255), nullable=False, comment='ID de la carpeta de Google Drive'),
    sa.Column('tipo_documento', sa.Enum('OFICIO', 'CAV', 'DESCONOCIDO', name='tipo_documento_enum'), nullable=False, comment='Tipo de documento (oficio, cav, desconocido)'),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ESPERANDO_PAR', 'PROCESANDO', 'COMPLETADO', 'ERROR', name='estado_documento_procesado_enum'), nullable=False, comment='Estado de procesamiento del documento'),
    sa.Column('par_documento_id', sa.Integer(), nullable=True, comment='ID del otro documento del par (self-referential)'),
    sa.Column('buffet_id', sa.Integer(), nullable=True, comment='ID del buffet asociado'),
    sa.Column('oficio_id', sa.Integer(), nullable=True, comment='ID del oficio creado desde este documento'),
    sa.Column('datos_extraidos_json', sa.Text(), nullable=True, comment='JSON con datos extraídos del documento'),
    sa.Column('error_mensaje', sa.Text(), nullable=True, comment='Mensaje de error si falla el procesamiento'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buffet_id'], ['buffets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['oficio_id'], ['oficios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['par_documento_id'], ['documentos_procesados.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_procesados_drive_file_id'), 'documentos_procesados', ['drive_file_id'], unique=True)
    op.create_index(op.f('ix_documentos_procesados_drive_folder_id'), 'documentos_procesados', ['drive_folder_id'], unique=False)
    op.create_index(op.f('ix_documentos_procesados_estado'), 'documentos_procesados', ['estado'], unique=False)
    op.create_index(op.f('ix_documentos_procesados_id'), 'documentos_procesados', ['id'], unique=False)
    op.create_index(op.f('ix_documentos_procesados_oficio_id'), 'documentos_procesados', ['oficio_id'], unique=False)
    op.create_index(op.f('ix_documentos_procesados_par_documento_id'), 'documentos_procesados', ['par_documento_id'], unique=False)
    op.create_index(op.f('ix_documentos_procesados_tipo_documento'), 'documentos_procesados', ['tipo_documento'], unique=False)
    op.alter_column('direcciones', 'resultado_verificacion',
               existing_type=postgresql.ENUM('PENDIENTE', 'EXITOSA', 'NO_ENCONTRADO', 'DIRECCION_INCORRECTA', 'SE_MUDO', 'RECHAZO_ATENCION', 'OTRO', name='resultado_verificacion_enum'),
               server_default=None,
               comment='Resultado de la última verificación',
               existing_comment='Resultado de la verificación',
               existing_nullable=False)
    op.alter_column('direcciones', 'fecha_verificacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de última verificación',
               existing_comment='Fecha y hora de verificación',
               existing_nullable=True)
    op.alter_column('direcciones', 'verificada_por_id',
               existing_type=sa.INTEGER(),
               comment='ID del usuario que realizó la verificación',
               existing_comment='ID del usuario que verificó la dirección',
               existing_nullable=True)
    op.alter_column('direcciones', 'cantidad_visitas',
               existing_type=sa.INTEGER(),
               server_default=None,
               comment='Número de visitas realizadas',
               existing_comment='Cantidad de visitas realizadas',
               existing_nullable=False)
    op.alter_column('vehiculos', 'oficio_id',
               existing_type=sa.INTEGER(),
               comment='ID del oficio (relación 1:N)',
               existing_comment='ID del oficio (relación 1:1)',
               existing_nullable=False)
    op.alter_column('visitas_direcciones', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='ID del investigador que visitó',
               existing_comment='ID del usuario que realizó la visita')
    op.alter_column('visitas_direcciones', 'fecha_visita',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='Fecha y hora de la visita',
               existing_nullable=False)
    op.alter_column('visitas_direcciones', 'resultado',
               existing_type=postgresql.ENUM('PENDIENTE', 'EXITOSA', 'NO_ENCONTRADO', 'DIRECCION_INCORRECTA', 'SE_MUDO', 'RECHAZO_ATENCION', 'OTRO', name='resultado_verificacion_enum'),
               comment='Resultado de esta visita',
               existing_comment='Resultado de la visita',
               existing_nullable=False)
    op.alter_column('visitas_direcciones', 'latitud',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=20),
               comment='Latitud GPS',
               existing_comment='Latitud GPS de la visita',
               existing_nullable=True)
    op.alter_column('visitas_direcciones', 'longitud',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=20),
               comment='Longitud GPS',
               existing_comment='Longitud GPS de la visita',
               existing_nullable=True)
    op.drop_constraint('visitas_direcciones_usuario_id_fkey', 'visitas_direcciones', type_='foreignkey')
    op.create_foreign_key(None, 'visitas_direcciones', 'usuarios', ['usuario_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visitas_direcciones', type_='foreignkey')
    op.create_foreign_key('visitas_direcciones_usuario_id_fkey', 'visitas_direcciones', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.alter_column('visitas_direcciones', 'longitud',
               existing_type=sa.String(length=20),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment='Longitud GPS de la visita',
               existing_comment='Longitud GPS',
               existing_nullable=True)
    op.alter_column('visitas_direcciones', 'latitud',
               existing_type=sa.String(length=20),
               type_=sa.DOUBLE_PRECISION(precision=53),
               comment='Latitud GPS de la visita',
               existing_comment='Latitud GPS',
               existing_nullable=True)
    op.alter_column('visitas_direcciones', 'resultado',
               existing_type=postgresql.ENUM('PENDIENTE', 'EXITOSA', 'NO_ENCONTRADO', 'DIRECCION_INCORRECTA', 'SE_MUDO', 'RECHAZO_ATENCION', 'OTRO', name='resultado_verificacion_enum'),
               comment='Resultado de la visita',
               existing_comment='Resultado de esta visita',
               existing_nullable=False)
    op.alter_column('visitas_direcciones', 'fecha_visita',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='Fecha y hora de la visita',
               existing_nullable=False)
    op.alter_column('visitas_direcciones', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='ID del usuario que realizó la visita',
               existing_comment='ID del investigador que visitó')
    op.alter_column('vehiculos', 'oficio_id',
               existing_type=sa.INTEGER(),
               comment='ID del oficio (relación 1:1)',
               existing_comment='ID del oficio (relación 1:N)',
               existing_nullable=False)
    op.alter_column('direcciones', 'cantidad_visitas',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               comment='Cantidad de visitas realizadas',
               existing_comment='Número de visitas realizadas',
               existing_nullable=False)
    op.alter_column('direcciones', 'verificada_por_id',
               existing_type=sa.INTEGER(),
               comment='ID del usuario que verificó la dirección',
               existing_comment='ID del usuario que realizó la verificación',
               existing_nullable=True)
    op.alter_column('direcciones', 'fecha_verificacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha y hora de verificación',
               existing_comment='Fecha y hora de última verificación',
               existing_nullable=True)
    op.alter_column('direcciones', 'resultado_verificacion',
               existing_type=postgresql.ENUM('PENDIENTE', 'EXITOSA', 'NO_ENCONTRADO', 'DIRECCION_INCORRECTA', 'SE_MUDO', 'RECHAZO_ATENCION', 'OTRO', name='resultado_verificacion_enum'),
               server_default=sa.text("'PENDIENTE'::resultado_verificacion_enum"),
               comment='Resultado de la verificación',
               existing_comment='Resultado de la última verificación',
               existing_nullable=False)
    op.drop_index(op.f('ix_documentos_procesados_tipo_documento'), table_name='documentos_procesados')
    op.drop_index(op.f('ix_documentos_procesados_par_documento_id'), table_name='documentos_procesados')
    op.drop_index(op.f('ix_documentos_procesados_oficio_id'), table_name='documentos_procesados')
    op.drop_index(op.f('ix_documentos_procesados_id'), table_name='documentos_procesados')
    op.drop_index(op.f('ix_documentos_procesados_estado'), table_name='documentos_procesados')
    op.drop_index(op.f('ix_documentos_procesados_drive_folder_id'), table_name='documentos_procesados')
    op.drop_index(op.f('ix_documentos_procesados_drive_file_id'), table_name='documentos_procesados')
    op.drop_table('documentos_procesados')
    # ### end Alembic commands ###

